name: cybersource_package
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: 4.8.1
  graphql: ^5.1.3
  hive: ^2.2.3
  mocktail: ^0.3.0
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  equatable: ^2.0.5
  http: ^1.1.0
  async: ^2.11.0
  flutter_secure_storage: ^9.0.0
  logger: ^1.3.0
  crypto: ^3.0.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  freezed: ^2.3.2
  build_runner: ^2.3.3
  melos: ^5.3.0
  mockito: ^5.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart